version: '3.8'
services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - micro-red

  cloud-gateway:
    build: ./cloud-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - micro-red

  buscador-service:
    build: ./buscador-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      - micro-red

  operador-service:
    build: ./operador-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    networks:
      - micro-red

networks:
  micro-red:
    driver: bridge
